[build]
  publish = "./"
  command = "# no build command"

[[redirects]]
  from = "/*"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.herokuapp.com/api/:splat"
  status = 200
  force = true 